PitBackRoom_MapScripts::
	.byte 0


PitBackRoom_EventScript_Nico::
	msgbox PitBackRoom_Text_Nico, MSGBOX_NPC
	end

PitBackRoom_Text_Nico:
	.string "Oh, uhm, hi!\n"
	.string "I'm Nico!\p"
	.string "I did a lot of the mapping for this\n"
	.string "game, as well as some of the Battle\l"
	.string "UI.\p"
	.string "Let me tell you, making maps is not\n"
	.string "easy!\p"
	.string "It might be called the Pit of 100\n"
	.string "Trials, but we didn't quite get to\l"
	.string "100 maps.\p"
	.string "Wanna know why?\p"
	.string "It's because we all are but unpaid\n"
	.string "volunteers, pouring our love into\l"
	.string "passion projects in the brief moments\l"
	.string "of respite that are allowed us when\l"
	.string "we're not busy being crushed by the\l"
	.string "cruel, cruel wheels of capitalism.\p"
	.string "… … …\p"
	.string "So I hope you enjoy our work!!!$"